### ISSUE TITLE
Filter get_avatar_url()

### ISSUE THREAD

**Issue by jaredatch** [strangerstudios/Basic-User-Avatars#13]
This function ignores our uploaded avatars since we do not filter it. Would be nice for us to do that.

https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/link-template.php#L3678

**Comment by kimcoleman** [comment]
We had a user comment on the .org support area that they need this feature as well. Internal discussions brought up whether updating the get_avatar method to instead be a filter on the get_avatar_data WP hook. This hook is used by both the get_avatar and get_avatar_url functions in WP so it would serve both purposes if we just use this single approach.

See: 
- function: https://developer.wordpress.org/reference/functions/get_avatar_data/
- filter hook: https://developer.wordpress.org/reference/hooks/get_avatar_data/

**Comment by kimcoleman** [comment]
This will be included in the next release. I am closing this issue now and will follow up in the Pull Request to be merged.
