### ISSUE TITLE
Shortcode Location

### ISSUE THREAD

**Issue by CFreeborn** [strangerstudios/Basic-User-Avatars#26]
Where does this shortcode go for a user forum? [basic-user-avatars] 
If I place it on the page with the forum short code it appears on the users page, rather than in their profile section where I'd like to see it.
Thanks

**Comment by jaredatch** [comment]
If you are using bbPress it should automatically be added to the edit profile screen.

**Comment by kimcoleman** [comment]
Hey @CFreeborn if you are still having an issue with this please comment below. I have just tested Basic User Avatars with bbPress and the Edit Profile screen properly shows the avatar field.

**Comment by kimcoleman** [comment]
I am going to close this issue as it has been some time. Please send us a message via our contact page for more guidance on using the plugin: https://www.strangerstudios.com/contact/
