### ISSUE TITLE
Abandonned project ?

### ISSUE THREAD

**Issue by Zazou89** [strangerstudios/Basic-User-Avatars#29]
Hello,

First for this really simple and **FREE** plugin ! But it seems abandonned :( 
Do you think, you'll update ?

thanks

**Comment by tlhInganHom** [comment]
I am wondering this too. It's been fine and stable for years, but with the latest Wordpress update, the image uploading is no longer working correctly for my PHP7 install.

**Comment by tlhInganHom** [comment]
To clarify, the image uploads into the directory, but the new image is not displayed in wordpress.

**Comment by andrewlimaza** [comment]
Hi @Galiwyx 

I've been recently assigned to help maintain and contribute to this plugin. An update will come out in the near future and we plan on maintaining this for further notice.

Please feel free to post any bugs you may encounter here - https://github.com/jaredatch/Basic-User-Avatars/issues/new

**Comment by Zazou89** [comment]
Hey,
Thank you for the answer !
