### ISSUE TITLE
Still deveolping this plugin? I have a couple of issues. 

### ISSUE THREAD

**Issue by hamish-strachan** [strangerstudios/Basic-User-Avatars#42]
Not sure if it's my set-up or because I'm using Oxygen Builder to build the site, but I have a couple of issues. They are both to do with using the shortcode on a page. 

I have included the shortcode in a modal that pops up when a user clicks 'Edit' on their profile page (a front-end page).

1: When a user uploads a new image, the page reloads and the image hasn't changed, but if I reload the page again, it changes. Possibly due to the pgae reloading while the image is still uploading? 

2: Once a user has set an avatar, when they try to replace it with a different one, the original image is still shown. Is this a permissions issue?

**Comment by kimcoleman** [comment]
The avatar not updating until you refresh is related in part to caching in your site and also because the modal avatar upload does not reload the page.

You will need to have the modal also reload the page or redirect back to it in some way for the new avatar to appear immediately for the user.
