### ISSUE TITLE
Downloaded but activation Fails

### ISSUE THREAD

**Issue by brittneyzellner** [strangerstudios/Basic-User-Avatars#45]
Parse error: syntax error, unexpected ')' in /home/awake934/dreamschooldiscipleship.com/wp-content/plugins/Basic-User-Avatars-master/init.php on line 520

**Comment by kimcoleman** [comment]
Please use the latest version from the Master branch here or download directly from WordPress.org here: https://wordpress.org/plugins/basic-user-avatars/. The current stable branch of this plugin does not have this error.
