### ISSUE TITLE
Add default avatar option

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/Basic-User-Avatars#70]
**Is your feature request related to a problem? Please describe.**
It would be helpful to generate a default avatar option ([.org request](https://wordpress.org/support/topic/generated-default-avatar-option/)).

> I’ve been using Avatar Privacy to handle my local avatars and improve the load time from the many Gravatar connection requests. 
> 
> It lacks the ability to let users upload avatars from the front end like say from the My Account page of Woocommerce Memberships.
> 
> One feature I do like however is that it generate different types of avatar family packs to make the local default set avatars more interesting, I presently use the “Rings” generated avatar pack which makes the website feel more dynamic when users haven’t set an avatar.
> 
> Is it possible to add something similar to this plugin?

**Describe the solution you'd like**
Add a feature to do this.

**Describe alternatives you've considered**
You should be able to use this filter with some other code to adjust the default image programmatically: https://github.com/strangerstudios/Basic-User-Avatars/blob/master/init.php#L233

**Comment by michaelbeil** [comment]
https://github.com/strangerstudios/Basic-User-Avatars/blob/master/init.php#L233

**Comment by andrewlimaza** [comment]
Here's a snippet - https://gist.github.com/andrewlimaza/f696ee7b8727f07ca1f473a0096a87a9
